[package]
edition = "2021"
name = "rusty-the-rogue"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "~0.8.7"
legion = "=0.4.0"

[dev-dependencies]
cargo-checkmate = "0.1.12"
